version: "3.8"
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: tutorial-nginx
    volumes:
      - ./app:/app
      - ./mydocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build: mydocker/php-fpm
    container_name: tutorial-php-fpm
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"

  mariadb:
    build: mydocker/mariadb
    container_name: tutorial-mariadb
    restart: always
    working_dir: /app
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
